namespace: vmware
name: alb
version: 1.0.0
readme: README.md
authors:
- Gaurav Rastogi <grastogi@vmware.com>
- Sandeep Bandi <sabandi@vmware.com>
- Amol Shinde <samol@vmware.com>
description: VMware Advanced Load Balancer (formerly Avi) Ansible Collection
license:
- GPL-2.0-or-later
license_file: 'LICENSE'
tags: [avi, controller, avicontroller, avisdk, avinetworks, networks, load, balancer, sdk]
repository: https://github.com/ansible-collections/vmware.nsx_alb
issues: https://github.com/ansible-collections/vmware.nsx_alb/issue

